# Generated by Django 6.0 on 2026-01-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('roll', models.IntegerField(null=True)),
                ('department', models.CharField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dob', models.DateField(null=True)),
            ],
        ),
    ]
